import Head from "next/head";
import { Client } from "@notionhq/client";
import { QueryDatabaseResponse } from "@notionhq/client/build/src/api-endpoints";
import React from "react";
import { Grid, Box, Tabs, Tab } from "@mui/material";

import classes from "../styles/index.module.css";
import MainTabs from "../components/mui/MainTabs";

export default function Home(props: { data: QueryDatabaseResponse }) {
  const data = props.data;
  console.log(data);
  return (
    <div>
      <Head>
        <title>sanghyeon.log</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        style={{
          background: "indianred",
          height: "30vh",
          marginBottom: "-50px",
        }}
      ></Box>
      <Box
        style={{
          fontSize: "5rem",
          paddingLeft: "calc(96px + env(safe-area-inset-left))",
        }}
      >
        <span>😀</span>
      </Box>
      <Box className={classes.mainPadding}>
        <Grid item xs={12}>
          <h1>sanghyeon.log</h1>
        </Grid>
      </Box>

      <main
        className={classes.mainPadding}
        style={{
          display: "flex",
          justifyContent: "center",
          width: "100%",
          paddingTop: "5px",
          flexDirection: "column",
        }}
      >
        <div
          style={{
            paddingTop: "8px",
            width: "100%",
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
          }}
        >
          <span className="database-title">TODAY I LEARNED</span>
        </div>
        <MainTabs />
      </main>

      <footer></footer>
    </div>
  );
}

export const getStaticProps = async () => {
  const notion = new Client({
    auth: process.env.NOTION_TOKEN,
  });

  const data = await notion.databases.query({
    database_id: process.env.DATABASE_ID as string,
    page_size: 10,
  });

  return {
    props: {
      data,
    },
  };
};
