import Head from 'next/head'
import {Client} from "@notionhq/client";
import {QueryDatabaseResponse} from "@notionhq/client/build/src/api-endpoints";
import React from "react";
import {Grid, Box} from "@mui/material";

export default function Home(props: {
  data: QueryDatabaseResponse
}) {
  const data = props.data;
  console.log(data)
  return (
    <div>
      <Head>
        <title>sanghyeon.log</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main>
        <Box style={{background: "indianred", height: "30vh", marginBottom: "-50px"}}></Box>
        <Box style={{fontSize: "5rem", paddingLeft: "calc(96px + env(safe-area-inset-left))"}}><span>😀</span></Box>
        <Grid item xs={12}>
          <h1>sanghyeon.log</h1>
        </Grid>
      </main>

      <footer>

      </footer>
    </div>
  )
}


export const getStaticProps = async () => {
  const notion = new Client({
    auth: process.env.NOTION_TOKEN,
  });

  const data = await notion.databases.query({
    database_id: process.env.DATABASE_ID as string
  });

  return {
    props: {
      data
    }
  }
}
